acme_topic:
    channel: 'acme/channel'
    handler:
        callback: 'acme.topic' #related to the getName of the topic

comment_topic:
    channel: 'comment/channel'
    handler:
        callback: 'comment.topic' #related to the getName of the topic

friendship_topic:
    channel: 'friendship/channel'
    handler:
        callback: 'friendship.topic' #related to the getName of the topic

conversation_topic:
    channel: conversation/channel
    handler:
        callback: 'conversation.topic'

# RPC stuff, don't touch this in case of just a topic
acme_rpc:
  channel: sample/{method}
  handler:
    callback: 'acme.rpc' #related to the getName
  requirements:
    method:
      pattern: "[a-z_]+" # pattern could be any valid regex

messages_manager_rpc:
  channel: messagesManager/{method}
  handler:
    callback: 'messages_manager.rpc'
  requirements:
    method:
      pattern: "[a-z_]+"

comment_manager_rpc:
  channel: commentManager/{method}
  handler:
    callback: 'comment_manager.rpc'
  requirements:
    method:
      pattern: "[a-z_]+"
